[[plugins]] # dein
repo = 'Shougo/dein.vim'

[[plugins]] # iceberg
repo = 'cocopon/iceberg.vim'
hook_add = '''
    autocmd MyAutoCmd ColorScheme * highlight Normal guibg=none
    autocmd MyAutoCmd ColorScheme * highlight EndOfBuffer guifg=#161821
    autocmd MyAutoCmd ColorScheme * highlight EndOfBuffer guibg=none
    autocmd MyAutoCmd ColorScheme * highlight CursorLineNr guifg=#777ea4
    autocmd MyAutoCmd ColorScheme * highlight SpecialKey guifg=#84a0c6
    autocmd MyAutoCmd ColorScheme * highlight SpecialKey guibg=none
    " replace #b4be82 to 94ce94
    autocmd MyAutoCmd ColorScheme * highlight MoreMsg guifg=#99c684
    autocmd MyAutoCmd ColorScheme * highlight PreProc guifg=#99c684
    autocmd MyAutoCmd ColorScheme * highlight Question guifg=#99c684
    autocmd MyAutoCmd ColorScheme * highlight Special guifg=#99c684
    autocmd MyAutoCmd ColorScheme * highlight diffAdded guifg=#99c684
    autocmd MyAutoCmd ColorScheme * highlight EasyMotionTarget guifg=#99c684
    autocmd MyAutoCmd ColorScheme * highlight GitGutterAdd guifg=#99c684
    let g:terminal_color_2 = '#99c684'

    autocmd MyAutoCmd VimEnter * nested colorscheme iceberg
    autocmd MyAutoCmd VimEnter * nested highlight clear CursorLine
'''

[[plugins]] # icons
repo = 'ryanoasis/vim-devicons'
depends = 'nerdtree'
hook_add = '''
    let g:WebDevIconsUnicodeDecorateFolderNodes = 1
'''

[[plugins]] # lightline
repo = 'itchyny/lightline.vim'
depends = ['vim-devicons', 'vim-fugitive', 'ale']
hook_add = '''
    let g:lightline = {
    \    'colorscheme' : 'iceberg',
    \    'active': {
    \       'left': [[ 'mode', 'paste' ], [ 'fugitive', 'readonly', 'filename', 'modified' ]],
    \       'right': [[ 'lineinfo' ], [ 'percent' ], [ 'fileformat', 'fileencoding', 'filetype'], [ 'linter_errors', 'linter_warnings', 'linter_ok' ]]
    \    },
    \    'component_function':{
    \       'fugitive': 'LightLineFugitive',
    \       'readonly': 'LightLineReadonly',
    \       'modified': 'LightLineModified',
    \       'filename': 'LightLineFilename',
    \       'filetype': 'LightLineFiletype',
    \       'fileformat': 'LightLineFileformat',
    \    },
    \    'component_expand': {
    \       'linter_warnings': 'LightlineLinterWarnings',
    \       'linter_errors': 'LightlineLinterErrors',
    \       'linter_ok': 'LightlineLinterOK'
    \    },
    \    'component_type': {
    \       'linter_warnings': 'warning',
    \       'linter_errors': 'error',
    \    },
    \    'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
    \    'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
    \ }

    function! LightLineModified()
        if &filetype == 'help'
            return ''
        elseif &modified
            return "\uf040"
        elseif &modifiable
            return ''
        else
            return ''
        endif
    endfunction

    function! LightLineReadonly()
        if &filetype == 'help'
            return ''
        elseif &readonly
            return "\uf023"
        else
            return ''
        endif
    endfunction

    function! LightLineFugitive()
        if &filetype !~? 'vimfiler\|gundo' && exists('*fugitive#head')
            let _ = fugitive#head()
            return strlen(_) ? "\ue725 "._ : ''
        else
            return ''
        endif
    endfunction

    function! LightLineFilename()
        return ('' != expand('%:p') ? winwidth(0) > 90 ? expand('%:p') : expand('%:t') : '[No Name]')
    endfunction

    function! LightLineFiletype()
      return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
    endfunction

    function! LightLineFileformat()
      return winwidth(0) > 70 ? (&fileformat . ' ' . WebDevIconsGetFileFormatSymbol()) : ''
    endfunction

    function! LightlineLinterErrors() abort
      let l:counts = ale#statusline#Count(bufnr(''))
      let l:all_errors = l:counts.error + l:counts.style_error
      let l:all_non_errors = l:counts.total - l:all_errors
      return l:all_errors == 0 ? '' : printf("\uf057 %d", all_errors)
    endfunction

    function! LightlineLinterWarnings() abort
      let l:counts = ale#statusline#Count(bufnr(''))
      let l:all_errors = l:counts.error + l:counts.style_error
      let l:all_non_errors = l:counts.total - l:all_errors
      return l:all_non_errors == 0 ? '' : printf("\uf06a %d", all_non_errors)
    endfunction

    function! LightlineLinterOK() abort
      let l:counts = ale#statusline#Count(bufnr(''))
      let l:all_errors = l:counts.error + l:counts.style_error
      let l:all_non_errors = l:counts.total - l:all_errors
      return l:counts.total == 0 ? "\uf058" : ''
    endfunction

    " hide --INSERT--
    set noshowmode
'''

[[plugins]] # quickrun
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = {
    \   'tex': {
    \       'command' : 'latexmk',
    \       'cmdopt' : '-pv',
    \       'exec' : '%c %o %s',
    \       'outputter' : 'error',
    \       'outputter/error/success' : 'null',
    \       'outputter/error/error' : 'quickfix',
    \       'srcfile' : expand("%"),
    \       'hook/sweep/files' : [
    \           '%S:p:r.aux',
    \           '%S:p:r.bbl',
    \           '%S:p:r.blg',
    \           '%S:p:r.dvi',
    \           '%S:p:r.fdb_latexmk',
    \           '%S:p:r.fls',
    \           '%S:p:r.log',
    \           '%S:p:r.out'
    \       ],
    \   },
    \}
'''

[[plugins]] # switch filetype
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
