[[plugins]] # dein
repo = 'Shougo/dein.vim'

[[plugins]] # Denite
repo = 'Shougo/denite.nvim'
hook_add = '''
    nnoremap sT :<C-u>Denite tab<CR>
    nnoremap sb :<C-u>Denite buffer_tab -buffer-name=file<CR>
    nnoremap sB :<C-u>Denite buffer -buffer-name=file<CR>
'''

[[plugins]] # lightline
repo = 'itchyny/lightline.vim'

[[plugins]] # iceberg
repo = 'cocopon/iceberg.vim'
hook_add = '''
    let g:lightline = {
        \ 'colorscheme' : 'iceberg',
        \ 'component': {
        \   'readonly': '%{&readonly?"x":""}',
        \ },
        \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
        \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
    \ }
'''

[[plugins]] # submode
repo = 'kana/vim-submode'
hook_add = '''
    call submode#enter_with('bufmove', 'n', '', 's>', '<C-w>>')
    call submode#enter_with('bufmove', 'n', '', 's<', '<C-w><')
    call submode#enter_with('bufmove', 'n', '', 's+', '<C-w>+')
    call submode#enter_with('bufmove', 'n', '', 's-', '<C-w>-')
    call submode#map('bufmove', 'n', '', '>', '<C-w>>')
    call submode#map('bufmove', 'n', '', '<', '<C-w><')
    call submode#map('bufmove', 'n', '', '+', '<C-w>+')
    call submode#map('bufmove', 'n', '', '-', '<C-w>-')
'''
