[[plugins]] # golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] #slim
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]] #javascript
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]] #jsx
repo = 'maxmellon/vim-jsx-pretty'
on_ft = 'javascript'

[[plugins]] #latex
repo = 'vim-latex/vim-latex'
hook_source = '''
    set shellslash
    set grepprg=grep\ -nH\ $*
    let g:tex_flavor='latex'
    let g:Imap_UsePlaceHolders = 1
    let g:Imap_DeleteEmptyPlaceHolders = 1
    let g:Imap_StickyPlaceHolders = 0
    let g:Tex_DefaultTargetFormat = 'dvi'
    let g:Tex_MultipleCompileFormats='dvi,pdf'
    let g:Tex_FormatDependency_pdf = 'dvi,pdf'
    let g:Tex_CompileRule_dvi = 'platex -synctex=1 -interaction=nonstopmode -file-line-error $*'
    let g:Tex_CompileRule_pdf = 'dvipdfmx $*.dvi'
    let g:Tex_BibtexFlavor = 'upbibtex'
    let g:Tex_MakeIndexFlavor = 'upmendex $*.idx'
    let g:Tex_UseEditorSettingInDVIViewer = 1
    let g:Tex_ViewRule_dvi = 'open -a /Applications/Skim.app'
    let g:Tex_ViewRule_pdf = 'open -a /Applications/Preview.app'
'''
