[[plugins]] # golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] #slim
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]] #javascript
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]] #jsx
repo = 'maxmellon/vim-jsx-pretty'
on_ft = 'javascript'

[[plugins]] #gnuplot
repo = 'vim-scripts/gnuplot.vim'
on_ft = 'gp'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
