[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # powerline
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {'colorscheme': 'wombat'}
'''

[[plugins]] # iceberg
repo = 'cocopon/iceberg.vim'
