#!/usr/bin/perl
$latex = 'platex -synctex=1 -halt-on-error %O %S';
$bibtex = 'pbibtex %O %B';
$dvipdf = 'dvipdfmx %O %S';
$max_repeat = 5;
$pdf_mode = 3; # use dvipdf
$pvc_view_file_via_temporary = 0;
$pdf_previewer = "open -ga /Applications/Skim.app";
